
Zname: residency
Yname: getting a job
Uname: motivation

Xsubject: people
Zsubject: people
Ysubject: people
Usubject: people


Y=1: gets a job
Y=0: doesn't get a job

Y=1_verb: get a job
Y=0_verb: don't get a job

Y=1_end: get a job
Y=0_end: don't get a job


Z=1: is a resident
Z=0: is not a resident

Z=1_verb: is a resident
Z=0_verb: is not a resident

#Z=1_head: For residents
#Z=0_head: For non-residents


U=1: is motivated
U=0: is not motivated

U=1_verb: is motivated
U=0_verb: is not motivated


graph: IV
queries: [ate]
roles: {treatment: X, outcome: Y, instrument: Z, confounder: U}


commonsense:
    Y|Z=1: [0.6, 0.9]
    Y|Z=0: [0.2, 0.5]
    X|Z=1: [0.4, 0.8]
    X|Z=0: [0.1, 0.3]


scenarios:
    1:
        Xname: training program A

        X=1: attending training program A
        X=0: not attending training program A

        X=1_verb: attends training program A
        X=0_verb: doesn't attend training program A

        X=1_end: attends training program A
        X=0_end: doesn't attend training program A

        do(X=1): attends training program A
        do(X=0): doesn't attend training program A


    2:
        Xname: training program B

        X=1: attending training program B
        X=0: not attending training program B

        X=1_verb: attends training program B
        X=0_verb: doesn't attend training program B

        X=1_end: attends training program B
        X=0_end: doesn't attend training program B

        do(X=1): attends training program B
        do(X=0): doesn't attend training program B







