
Zname: residency
Yname: getting a job
Uname: motivation


Y=1: gets a job
Y=0: doesn't get a job


Z=1: is a resident
Z=0: is not a resident


U=1: is motivated
U=0: is not motivated


graph: IV
queries: [ate]
roles: {treatment: X, outcome: Y, instrument: Z, confounder: U}


commonsense:
    Y|Z=1: [0.6, 0.9]
    Y|Z=0: [0.2, 0.5]
    X|Z=1: [0.4, 0.8]
    X|Z=0: [0.1, 0.3]


scenarios:
    1:
        Xname: training program A

        X=1: attending training program A
        X=0: not attending training program A

        do(X=1): attends training program A
        do(X=0): doesn't attend training program A


    2:
        Xname: training program B

        X=1: attending training program B
        X=0: not attending training program B

        do(X=1): attends training program B
        do(X=0): doesn't attend training program B







